[package]
name = "indodax-order"
version = "1.0.1"
edition = "2021"

[dependencies]
chrono = { workspace = true }
indodax-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
indodax-testkit = { workspace = true }
