[package]
name = "indodax-paper"
version = "1.0.1"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
indodax-core = { workspace = true }
indodax-execution = { workspace = true }
indodax-order = { workspace = true }
indodax-storage = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
indodax-testkit = { workspace = true }
